import React from "react";
import ReactDOM from "react-dom";

import Head from 'next/head'


import { ChakraProvider } from "@chakra-ui/react";







import Header from "../public/styles/header";
import SmallWithSocial from "../public/styles/footer";
import {Botao} from '../public/styles/OwnComponents'



function Home()
{
  return (
    <>
      <Head>
        <title>Kcalculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./logo.png" />
      </Head>
      

      <div class="container">
        <div class="header">
          

          <ChakraProvider>
            <Header />
          </ChakraProvider>

          
        </div>
        <div class="main">b</div>
        <div class="footer">
        <ChakraProvider>
            <SmallWithSocial />
          </ChakraProvider>
        </div>
      </div>
{/*
      <h1 className="title">MILKSHAKE</h1>
            <ChakraProvider>
              <Botao texto="Clique aqui"></Botao>

              <Input variant="flushed" placeholder="Nome" />
            </ChakraProvider>
      
  
        


        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
*/}
    </>
  )
}




export default Home;